# Generated by Django 5.1.4 on 2024-12-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ContactMessage',
        ),
    ]
