# Generated by Django 5.1.4 on 2024-12-20 06:42
# 历史迁移：将 ContactMessage 改回 Message，保持当前代码中的模型名称。

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact_message", "0002_rename_message_contactmessage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactMessage",
            new_name="Message",
        ),
    ]
