# Generated by Django 6.0.5 on 2026-06-01
# 将来源链接改为可选字段，支持原创或无外部来源的文章。

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="source_url",
            field=models.URLField(blank=True),
        ),
    ]
