# Generated by Codex on 2026-06-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_alter_article_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-is_pinned", "-published_date"]},
        ),
    ]
