# Generated by Codex on 2026-06-06

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models
import django.db.models.deletion


def backfill_article_author_user(apps, schema_editor):
    User = apps.get_model("users", "User")
    Article = apps.get_model("articles", "Article")

    user, created = User.objects.get_or_create(
        username="admin",
        defaults={
            "email": "admin@example.com",
            "is_staff": True,
            "is_superuser": True,
        },
    )
    if created:
        user.password = make_password(None)
        user.save(update_fields=["password"])

    Article.objects.filter(author_user__isnull=True).update(author_user=user)


def reverse_backfill_article_author_user(apps, schema_editor):
    Article = apps.get_model("articles", "Article")
    Article.objects.filter(author_user__username="admin").update(author_user=None)


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_article_author_user_is_pinned_is_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            backfill_article_author_user, reverse_backfill_article_author_user
        ),
        migrations.AlterField(
            model_name="article",
            name="author_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
